version: '3.7'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
